name: build

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3
      # - name: install and build
      #   run: |
      #     npm install -g pnpm
      #     pnpm install
      #     npm run build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          username: 'root' #ssh user name
          host: '118.195.232.109' #引用之前创建好的secret
          key: ${{ secrets.SSH_KEY }} #引用之前创建好的secret
          source: './'
          target: '/www/wwwroot/zhaohs'

      - name: build and run project
        uses: appleboy/ssh-action@master
        with:
          host: '118.195.232.109'
          username: 'root'
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /www/wwwroot/zhaohs
            pnpm install
            npm run build
            cp .env ./dist
            cp .env.production ./dist
            NODE_ENV=production pm2 restart ./dist/main.js --name zhaohs  --update-env
